version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  pg:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/pgdatabase:/var/lib/postgresql
    environment:
      POSTGRES_USER: 'andrii'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'test'
  my:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/mysqldatabase:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'mymoney'
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db/mongodatabase:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: pass
      REDIS_USER: h
